# U S Σ R Δ T O R / Ümüd & Sahib

from random import choice
from userbot.cmdhelp import CmdHelp
from userbot.events import register


DC_STRINGS = [
    "**⚡Ən böyük peşmançılıq çəkdiyin pislik nə olub?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Başıva un tök selfi elə şəklini hansısa qrupda paylaş**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡'Yox' demək istədiyiniz halda tez-tezmi 'hə' deyirsiniz? Bunun səbəbi nədir?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡İnstagram story-nə indiki oyunçulardan kiminsə şəklini qoy**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡Həyatınızda sizi həyəcanlandıran şey nədir?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡30 saniyə qurbağa təqlid səsini atın.**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡Səhra adasına düşsəniz hansı 3 şeyi nə götürəsiz?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡5 dəqiqədə Adınızı 'Mən bir eşşəyəm' edin**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡Səncə insan üçün ailəsindən sonra dini önəmli olmalıdı yoxsa milli kimliyi?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Son danışdığın insana 'Şəkil at' yaz**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡Etdiyiniz hansı səhvi daha təkrar etmirsiniz?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Küçəyə çıx və qarşına çıxan ilk insandan pul istə.😂💸**\n\n**Cəsarət** 📛 | @UseratorOT",    
    "**⚡Bütün dünya əhalisinə 30 saniyəlik müraciət etmək imkanınız olsaydı, həmin yarım dəqiqə ərzində nələr deyərdiniz?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Ən utandığın şəklini qrupa göndər!**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡Həyatınızdakı ən gözəl gün necə olub? Və niyə belə düşünürsünüz?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Gözünü bağla və 'elektrikləşdirilmişlərdənsinizmi' yaz.**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡Hesablayın, gündə neçə saat sosial şəbəkələrdə vaxt keçirirsiniz?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Yeri öp və bunu videoya çək göndər**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡Sonuncu dəfə nə vaxt və nəyə gözünüz yaşarana kimi gülmüsünüz?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Başına qazan qoy və şəklini çək göndər.**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡Hansı xoşagəlməz xüsusiyyətlərinizdən xilas olmaq istərdiniz?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Teleqramda bir qrupa link at**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡Acı təcrübələriniz sizə nələri öyrədib?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Birinin şəklini Profil Şəkilinə 10 dəqiqə qoyun**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡Elə şeylər varmı ki, hansı ki, düşünürsünüz ki, onları etməyə başlamaq üçün artıq gecikmisiniz? Nə üçün bu fikirdəsiniz?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Çiy yumurta iç və bunu videoya çək at.**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡10 il əvvələ qayıtsaydınız, hansı həyati dərsləri öyrənmək istərdiniz?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Google tarixçəsini screenshot elə at.**\n\n**Cəsarət** 📛 | @DTOUserBot", 
    "**⚡Nə vaxtsa kinoya baxanda və ya kitab oxuyanda gözlərindən yaş axıb?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Bir uşaq mahnısı oxuyaraq bir səs at.**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡Ən sevdiyin müğənni/qrup?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Qonşunun evinə get və çörək istə.**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡Bu qrupda səmimi olduğun ama sevmədiyin biri var?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Ümumi olaraq insanlarla münasibət və əlaqələriniz sizi qane edir?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Heç bitiniz olubmu?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Dostunla , Sevgilin ölüm ayağında olsa ilk kimi xilas edərdin?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Ən çox kiminlə fikirlərin ayrılır amma yenə də danışmağa davam edirsiz?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Xəyalındakı qız/oğlan necə biri ?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Heç vaxt etmərəm deyib etdiyiniz şey olub?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Qrupda düşüncə olaraq, özünə ən yaxın kimi görürsən?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Gələcəkdə hansı işlə məşğul olmaq istəyərsən?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Ailəndə səninlə bağlı elə hadisə olubmu ki, onu eşitməkdən bezmisən?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡İçkilib olub düşdüyün ən troll, gülünc vəziyyət?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Bu qrupda ən çox kimə dəyər verirsən?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Bu gecə öləcəyini bilsən, kimə və hansı vacib məsələ haqqında danışmaq istərdin?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Qarşı cinsə göndərdiyin ən son mesaj nə idi?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Elə şeylər varmı ki, hansı ki düşünürsünüz ki, onları etməyə başlamaq üçün artıq gecikmisiniz? Nə üçün bu fikirdəsiniz?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Utanarkən üzü qızarmayanlardansınızmı?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Zamanı daha sürətli və ya daha yavaş hala gətirə bilən gücün olsa, nə edərdin?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Sənə ən çox təsir edən qorxu filmi hansıdır? Səbəb?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Dünyadakı bütün televiziya və radio kanallarına eyni anda bir cümlə göndərə bilmə şansın olsa, bu, hansı cümlə olardı?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Qarşındakı insanın düzgün olmasını nədən seçirsən?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Qrupda ən çox dəyər verdiyin, bəyəndiyin, çox istədiyin insan kimdir? (Sıra ilə 3 nəfər)**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Birindən onu sevdiyini gizlətmisən?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Sizcə, bir insanı güvənsiz edən şeylər nədir?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Google da axtardığınız ən qəribə şey nədir?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Bir oturuma ən çox yediyin yemək hansı olub? Ətrafdan hansı reaksiyalar gəlib?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Fərz et ki, həyatının qalan hissəsində internetdə sadəcə bir (!) insanla mesajlaşa bilərsən. Bu kim olardı?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Məhşur biri ilə daha yaxın ola bilsəydin, kimi seçərdin?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Sizə yalan deyildiyində doğrusunu bilib, amma özünüzü inanırmış kimi  aparmısınız ?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Sənin ən sevdiyin yemək hansıdır?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Əsla bağlanmaram deyibdə bağlandığın biri olub?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Səni atıblar?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Biri ilə görüşməkdən qaçmaq üçün özünü xəstəliyə vurmusan?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡İnsanlara sevgi hissi verilməsəydi... Səncə dünyamız necə olardı?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Qrupda ən az kimi sevirsən?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Gələcəkdə evlənəcəyin insan nə desə fikrindən daşınarsan?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Cəhənnəmdə yanacağını bilsəydin səncə bu hansı günahına görə olardı?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Səncə Aldatmağ yoxsa Aldadılmağ daha rahatdır?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Səncə bu qrupdakı ən pis insan kim oLabiLər?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Gələcəyi görə bilmə bacarığın olsa,ən çox nəyi görmək istəyərdin?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Sizcə virtualda dostluq var?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Mahnıya ən çox nə zaman ehtiyac duyursan?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Həyatınıza alıbda peşman olduğunuz şəxs varmı?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Birisi sənə dünyanın ən varlı insanı olmağı təklif etsə əsla etmərəm dediyin şey nə olar?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Dostunuzu satmısınız?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Online dərsdə görüntünü bağlayıb yemək yediyiniz olub?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Öz-özünüzə danışırsınız? Ən çox nə haqqında?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Yadplanetlilərə inanırsan?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Heç dostunuzun sirrini başqası ilə bölüşmüsünüzmü?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Sizcə bir daha mahnıya qulaq asa bilməmək yoxsa bir daha şəkil çəkdirməmək?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Başqalarının məsləhətlərini dinləyirsiz?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Hər hansı bir heyvan ola bilsəydin, nə edərdin?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Heç gülünc vəziyyətə düşmüsünüz?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Əks cins kimi yuxudan ayılsan ilk nə edərdin?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Evlilik üçün ideal yaş?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Sizdən boyca balaca biri ilə sevgili olardız?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Dünyanın sonu belə gəlsə,heç vaxt etməyəcəyiniz şey nədir?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡İlan və ya qurbağa kimi şeylər yemisən?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Neçə uşaq sahibi olmaq istərdiniz?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Ən sevdiyin serial?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Hazırda kiminlə sevgilisən?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Heç ilk görüşdə aşiq oldunmu?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Hazırda kiminlə sevgilisən?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Bu qrupda səmimi olduğun ama sevmədiyin biri var?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Yaxın dostluq münasibəti qurmaq istədiyin bir kəs sənin haqqında nəyi bilməlidir?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Gizli sevgilin kimdir?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Anlaşılmayacağı dəqiq olsa,aldadardınız?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Ailəndə səninlə bağlı elə hadisə olubmu ki, onu eşitməkdən bezmisən?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Həyatda nə olmasa darıxdırıcı olar?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Gələcəkdə hansı işlə məşğul olmaq istəyərsən?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Ölüm sizcə nəyi ifadə edir?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡“Yox” demək istədiyiniz halda tez-tezmi “hə” deyirsiniz? Bunun səbəbi nədir?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Qrupdakı hər bir şəxs haqqında bir müsbət və bir mənfi şey söyləyin.**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Cəmiyyətdəki ən biabırçı anınız nə olub?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Valideynlərinin yanında səhvən söyüş söymüsən?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Dostunuzun və ya yaxınınızın etdiyi hər hansı bir səhvi üstünüzə götürmüsünüz?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Səs tonunu dəyişərək mahnı oxu at**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Xəstəxanadasan və təcili birinə böyrək lazımdı.Böyrəyini verərdin?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Əvvəldən səndən xoşu gələn birinin indi başqasınnan xoşu gəlsə qısqanarsan?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Heç kimin tapa bilməyəcəyi pis bir şey etdiniz?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Qrupda düşüncə olaraq, özünə ən yaxın kimi görürsən?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Səncə insanlara 2 ci şans vermək olar?(Niyə?)**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Başqaları sənlə danışanda, doğurdan da onları dinləyirsən?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Səncə insanlara 2 ci şans vermək olar?(Niyə?)**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Ən xoşladığınız aksesuar?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Qrupda xətri əziz olan 1 qız 1 oğlan adı de**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Heç vaxt etmərəm deyib etdiyiniz şey olub?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Xəyalındakı qız/oğlan necə biri ?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Qarşındakının yalan danışdığını bilsəydin nə edərdin?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Tərgidə bilmədiyin vərdiş?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Həyatındakı ən gözəl gün necə olub?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Ən çox kiminlə fikirlərin ayrılır amma yenə də danışmağa davam edirsiz?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Digər insanlardan fərqli olaraq nələr edirsən?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡İçində öldüyün tarixin yazılı olduğu bir zərf alsaydın,açıb baxardınmı?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Əgər görünməz olsaydın,bu oyundakılardan kimi izləmək istəyərdin?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Eyni sənə oxşayan adamla tanış olmaz istəyərsən?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Ən dəyərli xatirən hansıdır?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Yuxunda danışırsan?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Kiminsə həyatına burnuvu soxmağı xoşlayırsan?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Sevgi üçün hərşeyi edərəm ama “bunu” eləmərəm dediyin şey nədir?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Ümumi olaraq insanlarla münasibət və əlaqələriniz sizi qane edir?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Şəxsi inkişafınızda sizə daha çox nə kömək edir – özünüzə etdiyiniz çağırışlar, çətin sınaqlar, yoxsa həyatın xoş və rahat tərəfləri?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Whatsappda yaxın bir dostuna orqan mafiyası məni təhdid edir mənə borc 10 min manat lazımdır de**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡Hekayənə oğlansansa “Təbrik edin baba oluram” , qızsansa “Təbrik edin nənə oluram.” yaz**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡İki dənə bir-biri ilə əlaqəsiz olan sok adları de və onları qarışdırıb iç.**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡Just now şəkil at**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡Təkcə burnuvun şəklini çək at.**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡Ən xoşladığın mahnının nəqarətini oxu,səsini göndər**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡Zibil vedrəsinnən bir şey götür və onunla şəkil çəkdirib at**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡1 dilim çiy kartof ye**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡Ayaqyolunda su içirmiş kimi şəkil cək və instada post olaraq paylaş ss mütləq**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡Başıvı qaldır ilk gördüyün yerin şəklini çək at**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡Telegramda da istədiyin birinə nömrənin son iki rəqəmini yaz əvvəlini tapsan sənən sevgili olacam de**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡Telegramdakı kantaktinda 3cü adama səndən zəhləm gedir axmaq yaz+ss şərtilə**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡Dilivi dişlə və Mən nə qələt etdim cəsarət seçdim de.Səsli**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡Getdim, gördüm bir dərədə iki kar, kor, kürkü yırtıq kirpi var. Dişi kar, kor kürkü yırtıq kirpi erkək kar, kor, kürkü yırtıq kirpinin kürkünü yamamaqdansa, erkək kar, kor kürkü yırtıq kirpi dişi kar, kor kürküyırtıq kirpinin kürkünü yamayır. (səsli danış)**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡Dostuna “Mafia oynundakı məşuqə rolu kimisən lazımlısan amma heç kimə arzu eləmirəm səni” de**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡Qız və ya Oğlan seç zəng edib: “Kız soğan soy!Gerizekallıı” de**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡Müəllimlərindən birinə günüvün necə keçtiyi barəsində yaz.**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡Birinzə zəng et və Qaradəniz şivəsi ilə danış.**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡Ovucuna istiot tök(şəkil)+iylə (səs at)**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡Ən xoşladığın mahnının nəqarətini oxu,səsini göndər**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡Dəftərə öz şəkilini çək və göndər**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡Bir ədəd çiy yumurta iç vidiosunu qrupa at**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡Bir parça çiy ət ye**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡Whatsappda müəlliminə  “yaxşı dərs keçə bilmirsiz çox heyif” yaz**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡Oğlansansa qız,qızsansa oğlan birinin şəxsisinə yazıb,özünü təriflə**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡Qrupda kiməsə şeir yaz**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡İnstagramda ilk qarşına çıxan profilə sevgilini sevirəm yaz**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡1-dən 100 ə kimi say səs at**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡Telefonunun ekranını ss elə at**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡Hər hansı kitabda 13 cü səhfəni aç 2 ci sətir 3 cü sözü kontaktındakı birinə göndər**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡Lətifə danış(ses at)**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡Sondan əvvələ əlifbanı səsli oxu**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡Hansısa qrupa girib,“çəkilin kənara mən həkiməm” yaz**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡Evdəki ən acı şeydən ye ( bibər ,istiot və.s)**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡Tanımadığın birinə “Siqaret çəkmək sizin sağlamlığınıza ziyan vurur” yaz**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡Xəkandazla selfie çək qrupa at**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡Tanımadığın birinə “ehh,bizim vaxtlarımız 2-ci Qarabağ müharibəsi,Corona vaxtları idi.Siz hardan biləsiz” yaz.**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡İnstagram DM ss elə at.**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡Telegram Mesajlar (PM) - Bölməsini ss elə at.**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡Vhatsapp Mesajlar Bölməsini ss elə at.**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡Evdəki telefonlarda saatları bir saat geri çək və heç nə demə heçkimə**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡Statusa imkanlı qohumlarımdan xaiş edirəm mənə pul verin yaz**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡Soyuducunu aç ,qarşina çıxan ilk şeyi ye (yada) iç**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡Qruplardan birinə “daha dözə bilmirəm” yaz və qrupdan çıx**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡Tanımadığın birinə “Bu gün sizin həyatınızı qurtardım,mənə bir can borcunuz var” yaz**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡Çölə çıxıb qışqıraraq “Qarabağ Azərbaycandır” de**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡İndi bir şəkil çək at**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡Hər hansısa bir qrupun admininə məndə admin olmaq istəyirəm bunun üçün hansı sənədlər lazımdır yaz**\n\n**Cəsarət** 📛 | @UseratorOT",
]

@register(outgoing=True, pattern="^.dc$")
async def dsor(e):
    await e.edit(choice(DC_STRINGS))

DC18_STRINGS = [
    "**⚡Heç dil vurmusan/Çalmısan?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Çılpaq şəklini at**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡Bakirəsən?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Ah-uh səsləri çıxardıb və bunu səsə qeyd elə at**\n\n**Cəsarət** 📛 | @UseratorOT",
    "**⚡Sənin erogen bölgən hansıdır?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Sevgilinlə porno çəkərdinmi?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Dostunun lüt şəklini çəkmisən mi?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Dostunla cinsi əlaqəyə girərdin mi?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Sevgilin 69 pozası təklif etsəydi, onunla əlaqəyə girərdin mi?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Yoldaşını dostun ilə əlaqəyə girməsi üçün şərait yaradardın mı?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Cinsi əlaqədə olan zaman, metobalizm problemi yaşamısan?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Oğlan dostun ilə cinsi əlaqəyə girərsən?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Lezbiyanların cinsi əlaqəsinə münasibətin necədir?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Geylərin cinsi əlaqəsinə münasibətin necədir?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Hansısa dostun üçün cinsi əlaqə üçün ev tutmusan?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Kuni-yə münasibətin necədir?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Qarşı cins minet eləsə, təşəkkür mənasında kuni edərsən?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Hamamda özünü lüt çəkib sonra ona baxıb masturbasiya etmisən?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Nude çəkib oğlan dostuna atmısan?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Nude çəkib rəfiqənə atmısan?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡İnstagram storyndə kiməsə görə nude paylaşıb digər followerləri gizlətmisən?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Hansısa qız dostunun telefonunda onun nudelarını oğurlayıb özünə atmısan?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Sabun ilə masturbasiya etmisən?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Neçə müddətdən bir masturbasiya edirsən?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Masturbasiyaya münasibətin necədir?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Cinsi əlaqədən sonra, qız ilə görüşməkdən utanmısan?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Sizcə, bir insanı güvənsiz edən şeylər nədir?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Hansı porno aktrisası xoşuna gəlir?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Hansı porno aktyor xoşuna gəlir?**\n\n**Doğruluq** ✅ | @UseratorOT",
    "**⚡Hansı porno saytdan videolara baxırsan?**\n\n**Doğruluq** ✅ | @UseratorOT",
]

@register(outgoing=True, pattern="^.dc18$")
async def dsor(e):
    await e.edit(choice(DC18_STRINGS))

CmdHelp('dc').add_command(
    'dc', None, 'Doğruluq/Cəsarət suallarını,əmrlərini verər.'
).add_command(
    'dc18', None, 'Doğruluq/Cəsarət ama 18+'
).add()
